// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account/account.proto

package account

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MembershipType int32

const (
	MembershipType_UNKNOWN_MEMBERSHIP_TYPE MembershipType = 0
	MembershipType_NORMAL                  MembershipType = 1
	MembershipType_PREMIUM                 MembershipType = 2
)

var MembershipType_name = map[int32]string{
	0: "UNKNOWN_MEMBERSHIP_TYPE",
	1: "NORMAL",
	2: "PREMIUM",
}

var MembershipType_value = map[string]int32{
	"UNKNOWN_MEMBERSHIP_TYPE": 0,
	"NORMAL":                  1,
	"PREMIUM":                 2,
}

func (x MembershipType) String() string {
	return proto.EnumName(MembershipType_name, int32(x))
}

func (MembershipType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{0}
}

type GetUserInfoRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRequest) Reset()         { *m = GetUserInfoRequest{} }
func (m *GetUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRequest) ProtoMessage()    {}
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{0}
}

func (m *GetUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRequest.Unmarshal(m, b)
}
func (m *GetUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRequest.Merge(m, src)
}
func (m *GetUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRequest.Size(m)
}
func (m *GetUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRequest proto.InternalMessageInfo

func (m *GetUserInfoRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetUserInfoResponse struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Membership           MembershipType `protobuf:"varint,2,opt,name=membership,proto3,enum=account.MembershipType" json:"membership,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetUserInfoResponse) Reset()         { *m = GetUserInfoResponse{} }
func (m *GetUserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoResponse) ProtoMessage()    {}
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{1}
}

func (m *GetUserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoResponse.Unmarshal(m, b)
}
func (m *GetUserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetUserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoResponse.Merge(m, src)
}
func (m *GetUserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoResponse.Size(m)
}
func (m *GetUserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoResponse proto.InternalMessageInfo

func (m *GetUserInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserInfoResponse) GetMembership() MembershipType {
	if m != nil {
		return m.Membership
	}
	return MembershipType_UNKNOWN_MEMBERSHIP_TYPE
}

func init() {
	proto.RegisterEnum("account.MembershipType", MembershipType_name, MembershipType_value)
	proto.RegisterType((*GetUserInfoRequest)(nil), "account.GetUserInfoRequest")
	proto.RegisterType((*GetUserInfoResponse)(nil), "account.GetUserInfoResponse")
}

func init() { proto.RegisterFile("account/account.proto", fileDescriptor_d66906c5773c9d08) }

var fileDescriptor_d66906c5773c9d08 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x51, 0x4b, 0x02, 0x41,
	0x10, 0xf6, 0xa4, 0x94, 0xc6, 0x10, 0xd9, 0x0a, 0x25, 0x83, 0xc4, 0x27, 0x11, 0x5a, 0xc1, 0x1e,
	0x7a, 0x0c, 0x85, 0xab, 0xac, 0xee, 0x3c, 0x2e, 0x8f, 0xa8, 0x17, 0x39, 0x65, 0xda, 0xa4, 0xbb,
	0xdd, 0x6d, 0x77, 0xa5, 0xfa, 0xf7, 0xa1, 0xb7, 0x27, 0x4a, 0xbd, 0xec, 0xee, 0xcc, 0xf7, 0x7d,
	0x33, 0xdf, 0xec, 0xc0, 0x49, 0x3c, 0x9f, 0x8b, 0x25, 0x37, 0x3d, 0x7b, 0x53, 0xa9, 0x84, 0x11,
	0xa4, 0x6c, 0xc3, 0x76, 0x17, 0xc8, 0x2d, 0x9a, 0x48, 0xa3, 0x1a, 0xf1, 0x37, 0x11, 0xe2, 0xe7,
	0x12, 0xb5, 0x21, 0xc7, 0xb0, 0x6f, 0xc4, 0x07, 0xf2, 0x86, 0xd3, 0x72, 0x3a, 0x07, 0x61, 0x16,
	0xb4, 0x67, 0x70, 0xb4, 0xc3, 0xd5, 0x52, 0x70, 0x8d, 0x84, 0xc0, 0x1e, 0x8f, 0x53, 0xb4, 0xdc,
	0xf5, 0x9b, 0x5c, 0x01, 0xa4, 0x98, 0xce, 0x50, 0xe9, 0xf7, 0x85, 0x6c, 0x14, 0x5b, 0x4e, 0xa7,
	0xda, 0xaf, 0xd3, 0xdc, 0x83, 0xb7, 0x81, 0x26, 0x3f, 0x12, 0xc3, 0x2d, 0x6a, 0xf7, 0x06, 0xaa,
	0xbb, 0x28, 0x69, 0x42, 0x3d, 0xf2, 0x1f, 0xfc, 0xf1, 0xb3, 0x3f, 0xf5, 0x5c, 0x6f, 0xe8, 0x86,
	0x4f, 0x77, 0xa3, 0x60, 0x3a, 0x79, 0x09, 0xdc, 0x5a, 0x81, 0x00, 0x94, 0xfc, 0x71, 0xe8, 0x0d,
	0x1e, 0x6b, 0x0e, 0xa9, 0x40, 0x39, 0x08, 0x5d, 0x6f, 0x14, 0x79, 0xb5, 0x62, 0x3f, 0x82, 0xf2,
	0x20, 0xeb, 0x46, 0xee, 0xa1, 0xb2, 0x65, 0x9b, 0x34, 0x37, 0x36, 0xfe, 0x0e, 0x7e, 0x7a, 0xf6,
	0x3f, 0x98, 0x4d, 0xda, 0x2e, 0x0c, 0x15, 0x9c, 0x2f, 0x04, 0x65, 0x4a, 0xce, 0x29, 0x7e, 0xc7,
	0xa9, 0x4c, 0x50, 0xd3, 0xaf, 0x38, 0x49, 0xd0, 0xe4, 0xc2, 0xe1, 0xa1, 0xed, 0x1b, 0xac, 0x3e,
	0x3a, 0x70, 0x5e, 0xaf, 0x99, 0x10, 0x2c, 0x41, 0xca, 0x44, 0x12, 0x73, 0x46, 0x85, 0x62, 0xbd,
	0x95, 0x7e, 0x7d, 0x5c, 0x64, 0xda, 0x2c, 0x91, 0x17, 0xec, 0xd9, 0xa4, 0x2d, 0x38, 0x2b, 0xad,
	0x57, 0x76, 0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x84, 0xf3, 0x02, 0xb2, 0xcb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	// GetUserInfo returns the account info (premium or not) for a token.
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, "/account.Account/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	// GetUserInfo returns the account info (premium or not) for a token.
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _Account_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account/account.proto",
}
