apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${SERVICE_ACCOUNT_NAME}
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: ${PROJECT_NUM}-compute@developer.gserviceaccount.com
