// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/grpc/examples/wallet/wallet.proto

package wallet

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BalancePerAddress struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance              int64    `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalancePerAddress) Reset()         { *m = BalancePerAddress{} }
func (m *BalancePerAddress) String() string { return proto.CompactTextString(m) }
func (*BalancePerAddress) ProtoMessage()    {}
func (*BalancePerAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_782fdca5bdaace77, []int{0}
}

func (m *BalancePerAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalancePerAddress.Unmarshal(m, b)
}
func (m *BalancePerAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalancePerAddress.Marshal(b, m, deterministic)
}
func (m *BalancePerAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalancePerAddress.Merge(m, src)
}
func (m *BalancePerAddress) XXX_Size() int {
	return xxx_messageInfo_BalancePerAddress.Size(m)
}
func (m *BalancePerAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_BalancePerAddress.DiscardUnknown(m)
}

var xxx_messageInfo_BalancePerAddress proto.InternalMessageInfo

func (m *BalancePerAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *BalancePerAddress) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type BalanceRequest struct {
	IncludeBalancePerAddress bool     `protobuf:"varint,1,opt,name=include_balance_per_address,json=includeBalancePerAddress,proto3" json:"include_balance_per_address,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *BalanceRequest) Reset()         { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()    {}
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_782fdca5bdaace77, []int{1}
}

func (m *BalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest.Unmarshal(m, b)
}
func (m *BalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest.Marshal(b, m, deterministic)
}
func (m *BalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest.Merge(m, src)
}
func (m *BalanceRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest.Size(m)
}
func (m *BalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest proto.InternalMessageInfo

func (m *BalanceRequest) GetIncludeBalancePerAddress() bool {
	if m != nil {
		return m.IncludeBalancePerAddress
	}
	return false
}

type BalanceResponse struct {
	Balance              int64                `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Addresses            []*BalancePerAddress `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BalanceResponse) Reset()         { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()    {}
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_782fdca5bdaace77, []int{2}
}

func (m *BalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceResponse.Unmarshal(m, b)
}
func (m *BalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceResponse.Marshal(b, m, deterministic)
}
func (m *BalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceResponse.Merge(m, src)
}
func (m *BalanceResponse) XXX_Size() int {
	return xxx_messageInfo_BalanceResponse.Size(m)
}
func (m *BalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceResponse proto.InternalMessageInfo

func (m *BalanceResponse) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *BalanceResponse) GetAddresses() []*BalancePerAddress {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func init() {
	proto.RegisterType((*BalancePerAddress)(nil), "grpc.examples.wallet.BalancePerAddress")
	proto.RegisterType((*BalanceRequest)(nil), "grpc.examples.wallet.BalanceRequest")
	proto.RegisterType((*BalanceResponse)(nil), "grpc.examples.wallet.BalanceResponse")
}

func init() {
	proto.RegisterFile("proto/grpc/examples/wallet/wallet.proto", fileDescriptor_782fdca5bdaace77)
}

var fileDescriptor_782fdca5bdaace77 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0x41, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0xff, 0xd9, 0x60, 0x7f, 0xf7, 0x6e, 0x28, 0x06, 0xc1, 0xa2, 0x97, 0x52, 0x94, 0xf5,
	0x62, 0x2a, 0xf3, 0xe0, 0xc9, 0x83, 0x05, 0xf5, 0x68, 0xe9, 0x65, 0x20, 0x48, 0xc9, 0xda, 0x97,
	0x38, 0x88, 0x4d, 0x4d, 0x3a, 0xf4, 0x23, 0xfa, 0xb1, 0xa4, 0x4d, 0xaa, 0x93, 0x15, 0x3d, 0x79,
	0x69, 0xf3, 0xf2, 0xfe, 0xf2, 0x3c, 0x79, 0xe0, 0x81, 0x59, 0xa5, 0x55, 0xad, 0x22, 0xa1, 0xab,
	0x3c, 0xc2, 0x37, 0xfe, 0x5c, 0x49, 0x34, 0xd1, 0x2b, 0x97, 0x12, 0x6b, 0xf7, 0x63, 0x2d, 0x41,
	0x0f, 0x1a, 0x84, 0x75, 0x08, 0xb3, 0xbb, 0xe0, 0x0e, 0xf6, 0x63, 0x2e, 0x79, 0x99, 0x63, 0x82,
	0xfa, 0xba, 0x28, 0x34, 0x1a, 0x43, 0x3d, 0xf8, 0xcf, 0xed, 0xd1, 0x23, 0x3e, 0x09, 0xc7, 0x69,
	0x37, 0x36, 0x9b, 0xa5, 0xc5, 0xbd, 0x81, 0x4f, 0xc2, 0x61, 0xda, 0x8d, 0xc1, 0x3d, 0xec, 0x3a,
	0xa1, 0x14, 0x5f, 0xd6, 0x68, 0x6a, 0x7a, 0x05, 0xc7, 0xab, 0x32, 0x97, 0xeb, 0x02, 0x33, 0x07,
	0x65, 0x15, 0xea, 0x6c, 0x53, 0x79, 0x27, 0xf5, 0x1c, 0xb2, 0xf5, 0x88, 0x40, 0xc3, 0xde, 0xa7,
	0xa0, 0xa9, 0x54, 0x69, 0x70, 0xd3, 0x9d, 0x7c, 0x73, 0xa7, 0x37, 0x30, 0x76, 0xba, 0x68, 0xbc,
	0x81, 0x3f, 0x0c, 0x27, 0xf3, 0x19, 0xeb, 0x0b, 0xcc, 0xb6, 0x8c, 0xd2, 0xaf, 0x9b, 0xf3, 0x77,
	0x02, 0xa3, 0x45, 0xcb, 0xd1, 0x47, 0x98, 0xde, 0x62, 0x9d, 0x3f, 0x39, 0x9e, 0x9e, 0xfc, 0x28,
	0xe7, 0x32, 0x1f, 0x9d, 0xfe, 0x42, 0xd9, 0x20, 0xc1, 0x3f, 0x9a, 0xc1, 0x74, 0xc1, 0xff, 0x4c,
	0xfe, 0x9c, 0xc4, 0x1c, 0x0e, 0x57, 0xaa, 0x17, 0x8f, 0x27, 0x36, 0x62, 0xd2, 0xd4, 0x22, 0x21,
	0x0f, 0x97, 0x42, 0x29, 0x21, 0x91, 0x09, 0x25, 0x79, 0x29, 0x98, 0xd2, 0xc2, 0xb6, 0xa9, 0xf9,
	0x9c, 0xb9, 0x26, 0xf5, 0xd5, 0x6b, 0x39, 0x6a, 0x8b, 0x75, 0xf1, 0x11, 0x00, 0x00, 0xff, 0xff,
	0xd2, 0x19, 0xb9, 0xbc, 0x83, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletClient interface {
	// Unary RPC to fetch balancer of the account.
	FetchBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	// Server streaming RPC to watch the balance of the account.
	WatchBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (Wallet_WatchBalanceClient, error)
}

type walletClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletClient(cc grpc.ClientConnInterface) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) FetchBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/grpc.examples.wallet.Wallet/FetchBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) WatchBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (Wallet_WatchBalanceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Wallet_serviceDesc.Streams[0], "/grpc.examples.wallet.Wallet/WatchBalance", opts...)
	if err != nil {
		return nil, err
	}
	x := &walletWatchBalanceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Wallet_WatchBalanceClient interface {
	Recv() (*BalanceResponse, error)
	grpc.ClientStream
}

type walletWatchBalanceClient struct {
	grpc.ClientStream
}

func (x *walletWatchBalanceClient) Recv() (*BalanceResponse, error) {
	m := new(BalanceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WalletServer is the server API for Wallet service.
type WalletServer interface {
	// Unary RPC to fetch balancer of the account.
	FetchBalance(context.Context, *BalanceRequest) (*BalanceResponse, error)
	// Server streaming RPC to watch the balance of the account.
	WatchBalance(*BalanceRequest, Wallet_WatchBalanceServer) error
}

// UnimplementedWalletServer can be embedded to have forward compatible implementations.
type UnimplementedWalletServer struct {
}

func (*UnimplementedWalletServer) FetchBalance(ctx context.Context, req *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchBalance not implemented")
}
func (*UnimplementedWalletServer) WatchBalance(req *BalanceRequest, srv Wallet_WatchBalanceServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchBalance not implemented")
}

func RegisterWalletServer(s *grpc.Server, srv WalletServer) {
	s.RegisterService(&_Wallet_serviceDesc, srv)
}

func _Wallet_FetchBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).FetchBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.examples.wallet.Wallet/FetchBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).FetchBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_WatchBalance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BalanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WalletServer).WatchBalance(m, &walletWatchBalanceServer{stream})
}

type Wallet_WatchBalanceServer interface {
	Send(*BalanceResponse) error
	grpc.ServerStream
}

type walletWatchBalanceServer struct {
	grpc.ServerStream
}

func (x *walletWatchBalanceServer) Send(m *BalanceResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Wallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.examples.wallet.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchBalance",
			Handler:    _Wallet_FetchBalance_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchBalance",
			Handler:       _Wallet_WatchBalance_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/grpc/examples/wallet/wallet.proto",
}
